name: Actions Back et Front
jobs:
  Back:
    steps:
      - use checkout
      - run : pip install -r requirements.txt
      - run : pytest test
      - run : docker build -t Backend .
  Front:
    steps:
      - use checkout
      - run: *commande lancer test unitaire*
      - run : nmp install
      - run : ng build --prod
      - run : docker build -t Frontend .
