
name: Actions Back et Front et Deploy pour Terraform 
on:
  push:
    branches:
      - "main"
jobs:
  Back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : pip install -r requirements.txt
      - run : pytest test
      - run : docker build -t Backend .
      - run : docker login -u _json_key_base64 -p ${{ secrets.DOCKER_PASSWORD }} https://europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/whitehorse
  Front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : ng test
      - run : nmp install
      - run : ng build --prod
      - run : docker build -t Frontend .
  deploy:
    runs-on: ubuntu-latest
    needs:
      - Front
      - Back
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
      - run: terraform init
      - run: terraform apply -auto-approve -input=False
